
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.DriverManager;
import static java.sql.JDBCType.NULL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mania
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        i1price = new javax.swing.JLabel();
        i1qty = new javax.swing.JTextField();
        l4 = new javax.swing.JLabel();
        i1total = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        i2qty = new javax.swing.JTextField();
        i3qty = new javax.swing.JTextField();
        i4qty = new javax.swing.JTextField();
        i5qty = new javax.swing.JTextField();
        i2price = new javax.swing.JLabel();
        i3price = new javax.swing.JLabel();
        i4price = new javax.swing.JLabel();
        i5price = new javax.swing.JLabel();
        i2total = new javax.swing.JLabel();
        i3total = new javax.swing.JLabel();
        i4total = new javax.swing.JLabel();
        i5total = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TOTAL = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "item1", "item2", "item3", "item4", "item5", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        l1.setText("Price");

        l2.setText("Quantity");

        i1price.setText(" ");

        i1qty.setText("1");
        i1qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i1qtyActionPerformed(evt);
            }
        });

        l4.setText("Total");

        i1total.setText("0");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "item1", "item2", "item3", "item4", "item5" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "item1", "item2", "item3", "item4", "item5" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "item1", "item2", "item3", "item4", "item5" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "item1", "item2", "item3", "item4", "item5" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        i2qty.setText("1");
        i2qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i2qtyActionPerformed(evt);
            }
        });

        i3qty.setText("1");
        i3qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i3qtyActionPerformed(evt);
            }
        });

        i4qty.setText("1");
        i4qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i4qtyActionPerformed(evt);
            }
        });

        i5qty.setText("1");
        i5qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i5qtyActionPerformed(evt);
            }
        });

        i2price.setText(" ");

        i3price.setText(" ");

        i4price.setText(" ");

        i5price.setText(" ");

        i2total.setText("0");

        i3total.setText("0");

        i4total.setText("0");

        i5total.setText("0");

        jLabel1.setText("TOTAL");

        TOTAL.setText("0");

        jButton1.setText("Place order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(i1qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(i2price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(i3price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(i4price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(i5price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(i1price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(l2)
                                        .addComponent(i5qty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(i4qty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(i3qty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(i2qty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l4)
                    .addComponent(i1total)
                    .addComponent(i2total)
                    .addComponent(i3total)
                    .addComponent(i4total)
                    .addComponent(i5total)
                    .addComponent(TOTAL))
                .addGap(36, 36, 36))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {TOTAL, i1price, i1qty, i1total, i2qty, i2total, i3qty, i3total, i4qty, i4total, i5qty, i5total, l1, l2, l4});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l2)
                    .addComponent(l1)
                    .addComponent(l4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(i1qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(i1total)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(i1price)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i2price)
                    .addComponent(i2qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i2total))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i3price)
                    .addComponent(i3qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i3total))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i4price)
                    .addComponent(i4qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i4total))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i5price)
                    .addComponent(i5qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i5total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TOTAL)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {i1price, i1qty, i1total, l1, l2, l4});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void i5qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i5qtyActionPerformed
        // TODO add your handling code here:
        Object selected = jComboBox5.getSelectedItem();
        String s=(String) selected;
        //l4.setText(s);
        try{
            // TODO add your handling code here:
            //String s1=quantity.getText();

            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/Item", "APP", " ");
            Statement sc= conn.createStatement();
            ResultSet rc= sc.executeQuery("select * from ITEMS WHERE ITEMID = '"+s+"'");
            //String ss= rc.getString(1);
            //while(quantity.getText())

            while(rc.next())
            {
                String item = rc.getString(1);
                //String itemname = rc.getString(3);
                Integer price = rc.getInt(2);
                System.out.println(item);
                System.out.println(price);
                String pricee = String.valueOf(price);
                i5price.setText(pricee);
                //heading.setText(itemname);
                String quant=i5qty.getText();
                Integer qty=parseInt(quant);
                Integer totall = qty*price;
                String tot = String.valueOf(totall);
                i5total.setText(tot);
                String i1totall=i1total.getText();
                String i2totall=i2total.getText();
                String i3totall=i3total.getText();
                String i4totall=i4total.getText();
                String i5totall=i5total.getText();
                Integer i1=parseInt(i1totall);
                Integer i2=parseInt(i2totall);
                Integer i3=parseInt(i3totall);
                Integer i4=parseInt(i4totall);
                Integer i5=parseInt(i5totall);
                Integer total = i1+i2+i3+i4+i5;
                String Total = String.valueOf(total);
                TOTAL.setText(Total);
            }

        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_i5qtyActionPerformed

    private void i2qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i2qtyActionPerformed
        // TODO add your handling code here:
        Object selected = jComboBox2.getSelectedItem();
        String s=(String) selected;
        //l4.setText(s);
        try{
            // TODO add your handling code here:
            //String s1=quantity.getText();

            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/Item", "APP", " ");
            Statement sc= conn.createStatement();
            ResultSet rc= sc.executeQuery("select * from ITEMS WHERE ITEMID = '"+s+"'");
            //String ss= rc.getString(1);
            //while(quantity.getText())

            while(rc.next())
            {
                String item = rc.getString(1);
                //String itemname = rc.getString(3);
                Integer price = rc.getInt(2);
                System.out.println(item);
                System.out.println(price);
                String pricee = String.valueOf(price);
                i2price.setText(pricee);
                //heading.setText(itemname);
                String quant=i2qty.getText();
                Integer qty=parseInt(quant);
                Integer totall = qty*price;
                String tot = String.valueOf(totall);
                i2total.setText(tot);
                String i1totall=i1total.getText();
                String i2totall=i2total.getText();
                String i3totall=i3total.getText();
                String i4totall=i4total.getText();
                String i5totall=i5total.getText();
                Integer i1=parseInt(i1totall);
                Integer i2=parseInt(i2totall);
                Integer i3=parseInt(i3totall);
                Integer i4=parseInt(i4totall);
                Integer i5=parseInt(i5totall);
                Integer total = i1+i2+i3+i4+i5;
                String Total = String.valueOf(total);
                TOTAL.setText(Total);
            }

        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_i2qtyActionPerformed

    private void i1qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i1qtyActionPerformed
        // TODO add your handling code here:
        //jComboBox1=(JComboBox<String>) evt.getSource();
        Object selected = jComboBox1.getSelectedItem();
        String s=(String) selected;
        try{
            // TODO add your handling code here:
            //String s1=quantity.getText();

            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/Item", "APP", " ");
            Statement sc= conn.createStatement();
            ResultSet rc= sc.executeQuery("select * from ITEMS WHERE ITEMID = '"+s+"'");
            //String ss= rc.getString(1);
            //while(quantity.getText())

            while(rc.next())
            {
                String item = rc.getString(1);
                //String itemname = rc.getString(3);
                Integer price = rc.getInt(2);
                System.out.println(item);
                System.out.println(price);
                String pricee = String.valueOf(price);
                i1price.setText(pricee);
                //heading.setText(itemname);
                String quant=i1qty.getText();
                Integer qty=parseInt(quant);
                Integer totall = qty*price;
                String tot = String.valueOf(totall);
                i1total.setText(tot);
                String i1totall=i1total.getText();
                String i2totall=i2total.getText();
                String i3totall=i3total.getText();
                String i4totall=i4total.getText();
                String i5totall=i5total.getText();
                Integer i1=parseInt(i1totall);
                Integer i2=parseInt(i2totall);
                Integer i3=parseInt(i3totall);
                Integer i4=parseInt(i4totall);
                Integer i5=parseInt(i5totall);
                Integer total = i1+i2+i3+i4+i5;
                String Total = String.valueOf(total);
                TOTAL.setText(Total);

            }

        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_i1qtyActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        jComboBox1=(JComboBox<String>) evt.getSource();
        Object selected = jComboBox1.getSelectedItem();
        String s=(String) selected;
        //l4.setText(s);
        try{
            // TODO add your handling code here:
            //String s1=quantity.getText();

            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/Item", "APP", " ");
            Statement sc= conn.createStatement();
            ResultSet rc= sc.executeQuery("select * from ITEMS WHERE ITEMID = '"+s+"'");
            //String ss= rc.getString(1);
            //while(quantity.getText())

            while(rc.next())
            {
                String item = rc.getString(1);
               // String itemname = rc.getString(3);
                Integer price = rc.getInt(2);
                System.out.println(item);
                System.out.println(price);
                String pricee = String.valueOf(price);
                i1price.setText(pricee);
                //heading.setText(itemname);
                String quant=i1qty.getText();
                Integer qty=parseInt(quant);
                Integer totall = qty*price;
                String tot = String.valueOf(totall);
                i1total.setText(tot);
                String i1totall=i1total.getText();
                String i2totall=i2total.getText();
                String i3totall=i3total.getText();
                String i4totall=i4total.getText();
                String i5totall=i5total.getText();
                Integer i1=parseInt(i1totall);
                Integer i2=parseInt(i2totall);
                Integer i3=parseInt(i3totall);
                Integer i4=parseInt(i4totall);
                Integer i5=parseInt(i5totall);
                Integer total = i1+i2+i3+i4+i5;
                String Total = String.valueOf(total);
                TOTAL.setText(Total);

            }

        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        jComboBox2=(JComboBox<String>) evt.getSource();
        Object selected = jComboBox2.getSelectedItem();
        String s=(String) selected;
        //l4.setText(s);
        try{
            // TODO add your handling code here:
            //String s1=quantity.getText();

            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/Item", "APP", " ");
            Statement sc= conn.createStatement();
            ResultSet rc= sc.executeQuery("select * from ITEMS WHERE ITEMID = '"+s+"'");
            //String ss= rc.getString(1);
            //while(quantity.getText())

            while(rc.next())
            {
                String item = rc.getString(1);
                //String itemname = rc.getString(3);
                Integer price = rc.getInt(2);
                System.out.println(item);
                System.out.println(price);
                String pricee = String.valueOf(price);
                i2price.setText(pricee);
                //heading.setText(itemname);
                String quant=i2qty.getText();
                Integer qty=parseInt(quant);
                Integer totall = qty*price;
                String tot = String.valueOf(totall);
                i2total.setText(tot);
                String i1totall=i1total.getText();
                String i2totall=i2total.getText();
                String i3totall=i3total.getText();
                String i4totall=i4total.getText();
                String i5totall=i5total.getText();
                Integer i1=parseInt(i1totall);
                Integer i2=parseInt(i2totall);
                Integer i3=parseInt(i3totall);
                Integer i4=parseInt(i4totall);
                Integer i5=parseInt(i5totall);
                Integer total = i1+i2+i3+i4+i5;
                String Total = String.valueOf(total);
                TOTAL.setText(Total);
            }

        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO ad your handling code here:
        jComboBox3=(JComboBox<String>) evt.getSource();
        Object selected = jComboBox3.getSelectedItem();
        String s=(String) selected;
        //l4.setText(s);
        try{
            // TODO add your handling code here:
            //String s1=quantity.getText();

            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/Item", "APP", " ");
            Statement sc= conn.createStatement();
            ResultSet rc= sc.executeQuery("select * from ITEMS WHERE ITEMID = '"+s+"'");
            //String ss= rc.getString(1);
            //while(quantity.getText())

            while(rc.next())
            {
                String item = rc.getString(1);
                //String itemname = rc.getString(3);
                Integer price = rc.getInt(2);
                System.out.println(item);
                System.out.println(price);
                String pricee = String.valueOf(price);
                i3price.setText(pricee);
                //heading.setText(itemname);
                String quant=i3qty.getText();
                Integer qty=parseInt(quant);
                Integer totall = qty*price;
                String tot = String.valueOf(totall);
                i3total.setText(tot);
                String i1totall=i1total.getText();
                String i2totall=i2total.getText();
                String i3totall=i3total.getText();
                String i4totall=i4total.getText();
                String i5totall=i5total.getText();
                Integer i1=parseInt(i1totall);
                Integer i2=parseInt(i2totall);
                Integer i3=parseInt(i3totall);
                Integer i4=parseInt(i4totall);
                Integer i5=parseInt(i5totall);
                Integer total = i1+i2+i3+i4+i5;
                String Total = String.valueOf(total);
                TOTAL.setText(Total);

            }

        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        jComboBox4=(JComboBox<String>) evt.getSource();
        Object selected = jComboBox4.getSelectedItem();
        String s=(String) selected;
        //l4.setText(s);
        try{
            // TODO add your handling code here:
            //String s1=quantity.getText();

            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/Item", "APP", " ");
            Statement sc= conn.createStatement();
            ResultSet rc= sc.executeQuery("select * from ITEMS WHERE ITEMID = '"+s+"'");
            //String ss= rc.getString(1);
            //while(quantity.getText())

            while(rc.next())
            {
                String item = rc.getString(1);
                //String itemname = rc.getString(3);
                Integer price = rc.getInt(2);
                System.out.println(item);
                System.out.println(price);
                String pricee = String.valueOf(price);
                i4price.setText(pricee);
                //heading.setText(itemname);
                String quant=i4qty.getText();
                Integer qty=parseInt(quant);
                Integer totall = qty*price;
                String tot = String.valueOf(totall);
                i4total.setText(tot);
                String i1totall=i1total.getText();
                String i2totall=i2total.getText();
                String i3totall=i3total.getText();
                String i4totall=i4total.getText();
                String i5totall=i5total.getText();
                Integer i1=parseInt(i1totall);
                Integer i2=parseInt(i2totall);
                Integer i3=parseInt(i3totall);
                Integer i4=parseInt(i4totall);
                Integer i5=parseInt(i5totall);
                Integer total = i1+i2+i3+i4+i5;
                String Total = String.valueOf(total);
                TOTAL.setText(Total);
}

        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
        jComboBox5=(JComboBox<String>) evt.getSource();
        Object selected = jComboBox5.getSelectedItem();
        String s=(String) selected;
        //l4.setText(s);
        try{
            // TODO add your handling code here:
            //String s1=quantity.getText();

            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/Item", "APP", " ");
            Statement sc= conn.createStatement();
            ResultSet rc= sc.executeQuery("select * from ITEMS WHERE ITEMID = '"+s+"'");
            //String ss= rc.getString(1);
            //while(quantity.getText())

            while(rc.next())
            {
                String item = rc.getString(1);
                //String itemname = rc.getString(3);
                Integer price = rc.getInt(2);
                System.out.println(item);
                System.out.println(price);
                String pricee = String.valueOf(price);
                i5price.setText(pricee);
                //heading.setText(itemname);
                String quant=i5qty.getText();
                Integer qty=parseInt(quant);
                Integer totall = qty*price;
                String tot = String.valueOf(totall);
                i5total.setText(tot);
                String i1totall=i1total.getText();
                String i2totall=i2total.getText();
                String i3totall=i3total.getText();
                String i4totall=i4total.getText();
                String i5totall=i5total.getText();
                Integer i1=parseInt(i1totall);
                Integer i2=parseInt(i2totall);
                Integer i3=parseInt(i3totall);
                Integer i4=parseInt(i4totall);
                Integer i5=parseInt(i5totall);
                Integer total = i1+i2+i3+i4+i5;
                String Total = String.valueOf(total);
                TOTAL.setText(Total);
            }

        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void i3qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i3qtyActionPerformed
        // TODO add your handling code here:
        Object selected = jComboBox3.getSelectedItem();
        String s=(String) selected;
        //l4.setText(s);
        try{
            // TODO add your handling code here:
            //String s1=quantity.getText();

            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/Item", "APP", " ");
            Statement sc= conn.createStatement();
            ResultSet rc= sc.executeQuery("select * from ITEMS WHERE ITEMID = '"+s+"'");
            //String ss= rc.getString(1);
            //while(quantity.getText())

            while(rc.next())
            {
                String item = rc.getString(1);
                //String itemname = rc.getString(3);
                Integer price = rc.getInt(2);
                System.out.println(item);
                System.out.println(price);
                String pricee = String.valueOf(price);
                i3price.setText(pricee);
                //heading.setText(itemname);
                String quant=i3qty.getText();
                Integer qty=parseInt(quant);
                Integer totall = qty*price;
                String tot = String.valueOf(totall);
                i3total.setText(tot);
                String i1totall=i1total.getText();
                String i2totall=i2total.getText();
                String i3totall=i3total.getText();
                String i4totall=i4total.getText();
                String i5totall=i5total.getText();
                Integer i1=parseInt(i1totall);
                Integer i2=parseInt(i2totall);
                Integer i3=parseInt(i3totall);
                Integer i4=parseInt(i4totall);
                Integer i5=parseInt(i5totall);
                Integer total = i1+i2+i3+i4+i5;
                String Total = String.valueOf(total);
                TOTAL.setText(Total);

            }

        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_i3qtyActionPerformed

    private void i4qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i4qtyActionPerformed
        // TODO add your handling code here:
        Object selected = jComboBox4.getSelectedItem();
        String s=(String) selected;
        //l4.setText(s);
        try{
            // TODO add your handling code here:
            //String s1=quantity.getText();

            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/Item", "APP", " ");
            Statement sc= conn.createStatement();
            ResultSet rc= sc.executeQuery("select * from ITEMS WHERE ITEMID = '"+s+"'");
            //String ss= rc.getString(1);
            //while(quantity.getText())

            while(rc.next())
            {
                String item = rc.getString(1);
                //String itemname = rc.getString(3);
                Integer price = rc.getInt(2);
                System.out.println(item);
                System.out.println(price);
                String pricee = String.valueOf(price);
                i4price.setText(pricee);
                //heading.setText(itemname);
                String quant=i4qty.getText();
                Integer qty=parseInt(quant);
                Integer totall = qty*price;
                String tot = String.valueOf(totall);
                i4total.setText(tot);
                String i1totall=i1total.getText();
                String i2totall=i2total.getText();
                String i3totall=i3total.getText();
                String i4totall=i4total.getText();
                String i5totall=i5total.getText();
                Integer i1=parseInt(i1totall);
                Integer i2=parseInt(i2totall);
                Integer i3=parseInt(i3totall);
                Integer i4=parseInt(i4totall);
                Integer i5=parseInt(i5totall);
                Integer total = i1+i2+i3+i4+i5;
                String Total = String.valueOf(total);
                TOTAL.setText(Total);
}

        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_i4qtyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
                System.out.println("hii");
            
                Object selected1 = jComboBox1.getSelectedItem();
                String s1=(String) selected1;
                Object selected2 = jComboBox2.getSelectedItem();
                String s2=(String) selected2;
                Object selected3 = jComboBox3.getSelectedItem();
                String s3=(String) selected3;
                Object selected4 = jComboBox4.getSelectedItem();
                String s4=(String) selected4;
                Object selected5 = jComboBox1.getSelectedItem();
                String s5=(String) selected5;
                String t1= i1total.getText();
                String t2= i2total.getText();
                String t3= i3total.getText();
                String t4= i4total.getText();
                String t5= i5total.getText();
                Integer tot1 = parseInt(t1);
                Integer tot2 = parseInt(t2);
                Integer tot3 = parseInt(t3);
                Integer tot4 = parseInt(t4);
                Integer tot5 = parseInt(t5);
                
                
                
                
                String qt1= i1qty.getText();
                String qt2= i2qty.getText();
                String qt3= i3qty.getText();
                String qt4= i4qty.getText();
                String qt5= i5qty.getText();
                Integer qtot1 = parseInt(qt1);
                Integer qtot2 = parseInt(qt2);
                Integer qtot3 = parseInt(qt3);
                Integer qtot4 = parseInt(qt4);
                Integer qtot5 = parseInt(qt5);

            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/Item", "APP", " ");
            PreparedStatement rc= conn.prepareStatement("INSERT into FINALORDER VALUES('122','12','12')");
            //String ss= rc.getString(1);
            //while(quantity.getText())
           /* ResultSet re= sc.executeQuery("INSERT INTO FINALORDER VALUES('"+s2+"','"+tot2+"','"+qtot2+"')");
            ResultSet rf= sc.executeQuery("INSERT INTO FINALORDER VALUES('"+s3+"','"+tot3+"','"+qtot3+"')");
            ResultSet rg= sc.executeQuery("INSERT INTO FINALORDER VALUES('"+s4+"','"+tot4+"','"+qtot4+"')");
            ResultSet rh= sc.executeQuery("INSERT INTO FINALORDER VALUES('"+s5+"','"+tot5+"','"+qtot5+"')");
            */
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TOTAL;
    private javax.swing.JLabel i1price;
    private javax.swing.JTextField i1qty;
    private javax.swing.JLabel i1total;
    private javax.swing.JLabel i2price;
    private javax.swing.JTextField i2qty;
    private javax.swing.JLabel i2total;
    private javax.swing.JLabel i3price;
    private javax.swing.JTextField i3qty;
    private javax.swing.JLabel i3total;
    private javax.swing.JLabel i4price;
    private javax.swing.JTextField i4qty;
    private javax.swing.JLabel i4total;
    private javax.swing.JLabel i5price;
    private javax.swing.JTextField i5qty;
    private javax.swing.JLabel i5total;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l4;
    // End of variables declaration//GEN-END:variables
}
